# Data Science Olympics 2019, Paris and Berlin

The Data Science Olympics were held on May, 23rd 2019, simultaneously in Berlin and Paris.
Over 1000 data scientists participated. We had 2 hours to create the best predictive model.

In [1]:
# Libraries and options
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import log_loss
%matplotlib inline 
pd.set_option('display.max_columns', 500)
#pd.set_option('display.height', 500)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_colwidth', -1)

In [2]:
# Define the competition scorer
def competition_scorer(y_true, y_pred):
    return log_loss(y_true, y_pred, sample_weight=10**y_true)

In [3]:
data_path = '.'

In [4]:
# Train data
requests = pd.read_csv('./train_requests.csv', sep=',', low_memory=False, error_bad_lines=False)
X_train = requests.loc[:, requests.columns != 'granted_number_of_nights']
y_train = requests['granted_number_of_nights']

# Test data
requests_test = pd.read_csv('./test_requests.csv', sep=',', low_memory=False, error_bad_lines=False)
X_test = requests_test

b'Skipping line 31303: expected 24 fields, saw 49\nSkipping line 75954: expected 24 fields, saw 49\n'

# Exploratory analysis

In [5]:
X_test.dtypes

request_id                       object
animal_presence                  object
answer_creation_date             object
child_situation                  int64
child_to_come                    object
district                         int64
group_composition_id             int64
group_composition_label          object
group_creation_date              object
group_id                         object
group_main_requester_id          object
group_type                       object
housing_situation_id             int64
housing_situation_label          object
long_term_housing_request        object
number_of_underage               int64
request_backoffice_creator_id    object
request_creation_date            object
requester_type                   object
social_situation_id              object
town                             object
victim_of_violence               object
victim_of_violence_type          object
dtype: object

In [6]:
# Dimensions
print("Dimension X_train:", X_train.shape)
print("Dimension X_test:", X_test.shape)

Dimension X_train: (297739, 23)
Dimension X_test: (74189, 23)

In [7]:
y_train.value_counts()

0    145743
1    102201
2    46585
3    3210
Name: granted_number_of_nights, dtype: int64

In [8]:
X_train.info()
X_train.describe(include='all').T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297739 entries, 0 to 297738
Data columns (total 23 columns):
request_id                       297739 non-null object
animal_presence                  297739 non-null object
answer_creation_date             297739 non-null object
child_situation                  297739 non-null int64
child_to_come                    115453 non-null object
district                         297739 non-null int64
group_composition_id             297739 non-null int64
group_composition_label          297738 non-null object
group_creation_date              297738 non-null object
group_id                         297739 non-null object
group_main_requester_id          297739 non-null object
group_type                       297738 non-null object
housing_situation_id             297739 non-null int64
housing_situation_label          276802 non-null object
long_term_housing_request        90926 non-null object
number_of_underage               297739 non-null int64
request_backoffice_creator_id    297739 non-null object
request_creation_date            297739 non-null object
requester_type                   297739 non-null object
social_situation_id              297739 non-null object
town                             98051 non-null object
victim_of_violence               297738 non-null object
victim_of_violence_type          4984 non-null object
dtypes: int64(5), object(18)
memory usage: 52.2+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
request_id,297739,297739,8e091360305f9da031561b5eddb478ba,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
animal_presence,297739,2,f,296908,NaN,NaN,NaN,NaN,NaN,NaN,NaN
answer_creation_date,297739,277562,2019-01-01 07:00:00,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
child_situation,297739,NaN,NaN,NaN,-0.321184,4.08921,-1,-1,-1,-1,70
child_to_come,115453,2,f,107529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
district,297739,NaN,NaN,NaN,7045.22,46442.4,1,35,61,81,315842
group_composition_id,297739,NaN,NaN,NaN,27.9082,28.8707,-1,10,10,40,120
group_composition_label,297738,12,man alone,163208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_creation_date,297738,61766,2017-07-17 00:00:00.000,151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_id,297739,63140,26ea416385179d96f07aaca883dfeb19,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_main_requester_id,297739,60950,19f587b018a6410be66712171d654a11,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_type,297738,2,individual,213882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
housing_situation_id,297739,NaN,NaN,NaN,121.964,83.2314,10,10,170,200,220
housing_situation_label,276802,21,street,127315,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_term_housing_request,90926,2,f,75630,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_of_underage,297739,NaN,NaN,NaN,-0.575531,0.859217,-1,-1,-1,0,14
request_backoffice_creator_id,297739,1088,7c1f3fa2eb9a8779c8e83441317acb3d,3567,NaN,NaN,NaN,NaN,NaN,NaN,NaN
request_creation_date,297739,277725,2019-01-01 07:00:00,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
requester_type,297739,3,user,293409,NaN,NaN,NaN,NaN,NaN,NaN,NaN
social_situation_id,297739,63112,2b5e0d51245ed6c5d4b57edaef2b8392,266,NaN,NaN,NaN,NaN,NaN,NaN,NaN
town,98051,1168,Saint-Étienne,5734,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_of_violence,297738,2,f,292382,NaN,NaN,NaN,NaN,NaN,NaN,NaN
victim_of_violence_type,4984,6,woman,2700,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Utility function for sampling

In [9]:
def vm_show_sample(df, n = 10, cols = None):
  if(cols == None):
    cols = df.columns
  print(df.loc[:, cols].sample(n))

In [10]:
vm_show_sample(X_train, 10)

                              request_id animal_presence  \
376     d06e3b0bb395a124f97c991797bd737c  f
92138   79fcfeb5dcc3b103b9914e4d25cf0bca  f
147785  561c14a0989a1438f0f3c133f5ae7b32  f
23012   59c88514e2d287af5c47c49fb914ad0d  f
87882   94b9f53a8a019b247f17f7d3d590bb60  f
157458  43fce5852687ecdb7ac57fe7b22afd5b  f
64365   eb17a5f53f3932dba2b0531cc0e76ff3  f
123606  7f06179abf47b364c221c036c3dbd1c6  f
212105  a3e67a7c3c195a06fb4d6aba873f6887  f
16665   ed52383dd93187124c09499d8ede5318  f

           answer_creation_date  child_situation child_to_come  district  \
376     2019-02-25 14:22:07.133 -1                f             81
92138   2019-02-28 07:24:15.74  -1                NaN           46
147785  2019-03-29 15:23:21.752 -1                NaN           22
23012   2019-02-21 10:55:00.181 -1                NaN           80
87882   2019-02-21 07:33:53.349 -1                NaN           46
157458  2019-03-30 17:13:25.049 -1                NaN           13
64365   2019-02-13 09:03:15.702 -1                NaN           60
123606  2019-03-08 11:20:57.916 -1                NaN           96
212105  2019-01-03 07:36:44.726 -1                f             61
16665   2019-02-20 16:24:26.747 -1                f             34

        group_composition_id        group_composition_label  \
376     10                    man alone
92138   40                    single mother with child(ren)
147785  20                    woman alone
23012   10                    man alone
87882   80                    isolated child/underage
157458  10                    man alone
64365   10                    man alone
123606  100                   couple with child(ren)
212105  10                    man alone
16665   10                    man alone

            group_creation_date                          group_id  \
376     2018-12-29 16:54:33.856  46e2fff8eebb6f0507850901b5e1fdc8
92138   2019-02-15 09:46:32.438  7fcbfcc0cb3cab34bddd154504b522b8
147785  2018-09-14 12:38:45.452  a9b79c6f4d93cd066a3e3d28a6567a8d
23012   2018-09-14 15:01:48.412  2d2d9d499662726566b2bf79cd97638c
87882   2018-02-27 11:33:12.476  cad912421948a525957da45a973ec790
157458  2019-03-30 17:16:15.962  de7972197cfea6286cf6c48dcf06017c
64365   2019-01-08 17:03:21.953  0fa8fd23e3d35c2b4e06b56ee2f4f9f7
123606  2018-11-28 11:06:54.704  1861db4d69a8e635fe8531b933adae18
212105  2018-12-16 21:48:00.259  425b5bf10e4bc15597817f54ab5299dc
16665   2017-08-12 00:00:00.000  4ced3d350e49cd0181023dc6e14f5178

                 group_main_requester_id  group_type  housing_situation_id  \
376     a4dc4fc184a6681ed45aaf48810d54b2  individual  10
92138   836110a06a371e4a0c4593f6884e48d8  group       10
147785  739dac52959cd6166dffadd340731949  individual  10
23012   8a1cb8ff169bc49e9396ce27d3103566  individual  200
87882   986fb0833906d083ab8e069e64c6b329  individual  10
157458  a27b6feee20ad64180fc61adfc12567c  individual  200
64365   2b8fa5c24738c7f5d503de0ac087f218  individual  200
123606  1456a880d2f1081c026da09f0df1568f  group       50
212105  5487742a01fffcc8db7e50cae2f4e482  individual  10
16665   bc5db4116f7aa6aa16a59cf0976fbdb0  individual  200

                   housing_situation_label long_term_housing_request  \
376     emergency structure                 f
92138   emergency structure                 NaN
147785  emergency structure                 NaN
23012   street                              NaN
87882   emergency structure                 NaN
157458  street                              NaN
64365   street                              NaN
123606  hotel paid by the emergency centre  NaN
212105  emergency structure                 t
16665   street                              NaN

        number_of_underage     request_backoffice_creator_id  \
376    -1                   47ee054ea9005210e06917c15b31137f
92138  -1                   73e6aab5f5697ca11492ffc1243b9902
147785 -1                   f683eb41f6522fb56801a5ca4494a07c
23012  -1                   c4aa3a7945b8a3b158c8b937db202eb3
87882  -1                   c8ee98d6e836cec8465e830f34aca00c
157458 -1                   242573cd2df8ef947bd8ea07b87598c8
64365  -1                   fc18817b7d0f3f86983f94e764b9d74a
123606 -1                   fab6d0fa277c3e7f2a74ccbe6e76cbe3
212105  0                   506ad05b97dfd5a92db3254eca78e5f1
16665  -1                   8cb394b634a69f573bf76928cc8e932c

          request_creation_date requester_type  \
376     2019-02-25 14:22:07.133  user
92138   2019-02-28 07:24:15.74   user
147785  2019-03-29 15:23:21.752  user
23012   2019-02-21 10:55:00.181  user
87882   2019-02-21 07:33:53.349  user
157458  2019-03-30 17:13:25.049  user
64365   2019-02-13 09:03:15.702  user
123606  2019-03-08 11:20:57.916  user
212105  2019-01-03 07:36:44.726  user
16665   2019-02-20 16:24:26.747  user

                     social_situation_id       town victim_of_violence  \
376     272cf95f2617610fa8ab30ac1f780745  Amiens     f
92138   8ede00c14c510d9ba2c803d1225bfb96  NaN        f
147785  fa42c30c677dd91d0fd5c8f26271f7e9  NaN        f
23012   b891b968a9a78fdc584aa5223182f0fe  NaN        f
87882   f9aa0e65e21c31cb182994a2d4c9b845  NaN        f
157458  a84a79efc1fc703c1d86e5ed6a14b7a4  NaN        f
64365   fa731c968b187931581376289c0b86a5  NaN        f
123606  c113c6aa4985f56b63f88bce482d9038  NaN        f
212105  4b943dd64b65edf418741175cedf9f56  Compiègne  f
16665   06c2e462080b57d7a660b88a8cd0a278  Caen       f

       victim_of_violence_type
376     NaN
92138   NaN
147785  NaN
23012   NaN
87882   NaN
157458  NaN
64365   NaN
123606  NaN
212105  NaN
16665   NaN

## Utility function for exploring unique values

In [11]:
# Explore top values for each column
def vm_show_value_counts(df, top_n):
  for col in df.columns:
    print('Top ' + str(top_n) + ' values for ' + col)
    vals = df[col].value_counts(dropna = False)
    if top_n != -1:
      vals = vals.iloc[:top_n]
    print(vals)
    print('\n')

In [12]:
vm_show_value_counts(X_train, 10)

Top 10 values for request_id
8e091360305f9da031561b5eddb478ba    1
cc8e0cf2b4dcddbd267e56a0fb057869    1
681d3109d479b6f5c42740a023a29a24    1
c3c78a413a797c294e113d869c76c9df    1
80923f71390138f73dbfb0935fdcc8be    1
7d20b674317274f02ac631c991c1524d    1
020177fbeadad774bc454de6813f67c6    1
74e1e52117def9efd091f65dfe186c7c    1
90620d5cb166fd996092107a6b6043ea    1
c867f44d93b8872c89e58658b6bc2b58    1
Name: request_id, dtype: int64


Top 10 values for animal_presence
f    296908
t    831
Name: animal_presence, dtype: int64


Top 10 values for answer_creation_date
2019-01-01 07:00:00    92
2019-02-06 09:00:00    71
2019-02-05 09:00:00    66
2019-03-24 21:00:00    64
2019-02-04 09:00:00    63
2019-02-26 09:00:00    62
2019-02-12 08:00:00    60
2019-01-07 09:00:00    60
2019-01-11 09:00:00    59
2019-02-12 09:00:00    57
Name: answer_creation_date, dtype: int64


Top 10 values for child_situation
-1     285079
 10    10139
 30    1047
 20    702
 70    304
 40    277
 50    121
 60    70
Name: child_situation, dtype: int64


Top 10 values for child_to_come
NaN    182286
f      107529
t      7924
Name: child_to_come, dtype: int64


Top 10 values for district
70    15587
68    14304
13    13147
60    12031
93    9994
34    9584
95    9524
81    8664
92    8440
96    8260
Name: district, dtype: int64


Top 10 values for group_composition_id
10     163208
20     45131
40     27912
100    27520
30     11974
60     8150
70     6367
80     3760
50     1853
120    1681
Name: group_composition_id, dtype: int64


Top 10 values for group_composition_label
man alone                        163208
woman alone                      45131
single mother with child(ren)    27912
couple with child(ren)           27520
couple without whildren          11974
group with child(ren)            8150
group of adults                  6367
isolated child/underage          3760
single father with child(ren)    1853
child/underage with family       1681
Name: group_composition_label, dtype: int64


Top 10 values for group_creation_date
2017-07-17 00:00:00.000    151
2017-07-26 00:00:00.000    130
2016-06-21 00:00:00.000    94
2018-01-17 00:00:00.000    89
2016-08-31 00:00:00.000    84
2016-10-08 00:00:00.000    81
2016-08-09 00:00:00.000    81
2017-05-22 00:00:00.000    81
2018-10-09 16:13:07.157    81
2017-07-27 00:00:00.000    79
Name: group_creation_date, dtype: int64


Top 10 values for group_id
26ea416385179d96f07aaca883dfeb19    81
a4f43b552acd9d88e844516a4522e51f    78
52c7ff7ca35bb3777d1b09cee8eab9f8    77
a4ae5f9cf0644917d2303ab293bb06ac    77
9761694d82a89191dd26e015124380a0    76
d3940e9088c1262ffeb77cb33d8c005e    76
97b0b0831031fa12a9f2d503dd23561a    76
b80579eac919428a09d131217ab05bfe    76
b38c3fedf42bd6a8b5a6d8e1823f385d    75
8ed515c1fcd585c981eda74c42bd53a0    75
Name: group_id, dtype: int64


Top 10 values for group_main_requester_id
19f587b018a6410be66712171d654a11    81
151b339666f6f77091411e78612c6202    78
cd7490380663afdefc5b28b900a426de    77
bc94870abcfc277feab94bb6c53789b4    77
483f912c9978afde2ea0c4f3bdfbff61    76
18303cf60f5d68b44660c61a8857a431    76
b85630e0c55c81c2cf0c2c593d2dfdfe    76
f9a5c75f9df301ebdc47e567cea7a0ff    76
0cf9cb7e270a10c897245f8a85a72332    75
3d575e45fdf56a4c1736fd0b77216300    75
Name: group_main_requester_id, dtype: int64


Top 10 values for group_type
individual    213882
group         83856
NaN           1
Name: group_type, dtype: int64


Top 10 values for housing_situation_id
200    127315
10     85732
50     21186
170    20937
160    11843
120    11454
100    5256
110    3566
130    2702
80     2135
Name: housing_situation_id, dtype: int64


Top 10 values for housing_situation_label
street                                127315
emergency structure                   85732
hotel paid by the emergency centre    21186
NaN                                   20937
other                                 11843
accomodation by a third party         11454
shelters                              5256
mobile or makeshift shelter           3566
public hospital                       2702
personal or marital home              2135
Name: housing_situation_label, dtype: int64


Top 10 values for long_term_housing_request
NaN    206813
f      75630
t      15296
Name: long_term_housing_request, dtype: int64


Top 10 values for number_of_underage
-1    212698
 0    63516
 1    9833
 2    6251
 3    3767
 4    1011
 5    454
 6    108
 7    85
 8    9
Name: number_of_underage, dtype: int64


Top 10 values for request_backoffice_creator_id
7c1f3fa2eb9a8779c8e83441317acb3d    3567
9b570744f75f9123aa9e961d15feb9c1    3096
3a6a8be575dcf96e80b5937ff16d59b3    2831
67db4a7b1325eab1f12264fef49d6fe8    2813
c1416118b9a90878748e05882334d1b8    2781
4083850101f6848cf7dbb8681261cf10    2525
63e83fbbebdabecde1fe46696f811ed0    2489
addadf6ec335d10a1aca7c3929a9d589    2274
3786c2f5ebe8a3171c1bcdf67209f151    2233
b0eb94003793100292db01690de60c62    2210
Name: request_backoffice_creator_id, dtype: int64


Top 10 values for request_creation_date
2019-01-01 07:00:00    92
2019-02-06 09:00:00    71
2019-02-05 09:00:00    66
2019-03-24 21:00:00    64
2019-02-04 09:00:00    63
2019-02-26 09:00:00    62
2019-01-07 09:00:00    60
2019-02-12 08:00:00    60
2019-01-11 09:00:00    59
2019-02-12 09:00:00    57
Name: request_creation_date, dtype: int64


Top 10 values for requester_type
user             293409
third party      3992
social patrol    338
Name: requester_type, dtype: int64


Top 10 values for social_situation_id
2b5e0d51245ed6c5d4b57edaef2b8392    266
4699888c7851089a1cb88e06f3bb77b7    81
4fb48de101a4c96253ab98cd590be215    78
84057b6d8da1442636e0cf4fd9685e56    77
2a389c242f8bb67a21f3bd803ddfcbf4    77
ab47ebf98b67b16f6e51465dbf23e811    76
4cdcdd108914c5f40a46fe790b3681c9    76
abc735f800ed07e9abafe1d772cf9706    76
ba50eb5b7f939040122252e5cff3e691    76
a0ac09ae0cdccf51db62b6046641f924    75
Name: social_situation_id, dtype: int64


Top 10 values for town
NaN              199688
Saint-Étienne    5734
Amiens           4945
Nantes           4785
Lyon             4594
Bordeaux         4197
Rennes           3828
Marseille        3721
Beauvais         3648
Grenoble         3624
Name: town, dtype: int64


Top 10 values for victim_of_violence
f      292382
t      5356
NaN    1
Name: victim_of_violence, dtype: int64


Top 10 values for victim_of_violence_type
NaN                                  292755
woman                                2700
woman victim of domestic violence    1587
man                                  410
family                               192
man victim of domestic violence      55
child                                40
Name: victim_of_violence_type, dtype: int64

In [13]:
def vm_count_unique(df):
    #res = df.loc[:, df.dtypes == 'object'].apply(lambda x : x.nunique())
    res = df.apply(lambda x : x.nunique())
    return res

In [14]:
vm_count_unique(X_train)

request_id                       297739
animal_presence                  2
answer_creation_date             277562
child_situation                  8
child_to_come                    2
district                         102
group_composition_id             13
group_composition_label          12
group_creation_date              61766
group_id                         63140
group_main_requester_id          60950
group_type                       2
housing_situation_id             22
housing_situation_label          21
long_term_housing_request        2
number_of_underage               13
request_backoffice_creator_id    1088
request_creation_date            277725
requester_type                   3
social_situation_id              63112
town                             1168
victim_of_violence               2
victim_of_violence_type          6
dtype: int64

# Preprocessing

## Choose features

In [15]:
#cat_cols = X_train.columns[X_train.dtypes == 'object']
my_cat_cols = my_cat_cols = ['animal_presence', 'child_situation', 'child_to_come', 'group_composition_id', 'group_type', 'housing_situation_id',
               'long_term_housing_request', 'number_of_underage', 'requester_type', 'victim_of_violence', 'victim_of_violence_type']

## Fill missing values in categorical variables

In [16]:
X_train = X_train.loc[:, my_cat_cols]
X_test = X_test.loc[:, my_cat_cols]

In [17]:
X_train.dtypes

animal_presence              object
child_situation              int64
child_to_come                object
group_composition_id         int64
group_type                   object
housing_situation_id         int64
long_term_housing_request    object
number_of_underage           int64
requester_type               object
victim_of_violence           object
victim_of_violence_type      object
dtype: object

In [18]:
for col in X_train.columns:
    if X_train[col].dtype == 'int64':
        X_train[col] = X_train[col].astype(str)
        X_test[col] = X_test[col].astype(str)

In [19]:
def vm_fill_missing(df, cols):
  res = df.copy(deep = True)
  for col in cols:
    res[col] = res[col].fillna('ZZmissing')
  return res

In [20]:
X_train = vm_fill_missing(X_train, my_cat_cols)
X_test = vm_fill_missing(X_test, my_cat_cols)

## Prepare weights and OH encoding

In [21]:
original_train_weights = 10 ** y_train

In [22]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X_train_enc = enc.fit_transform(X_train)
X_test_enc = enc.transform(X_test)

In [23]:
X_train_aug = np.concatenate([np.array(pd.DataFrame({'weight':original_train_weights})), X_train_enc.toarray()], axis = 1)

## CV split

In [24]:
from sklearn.model_selection import train_test_split

In [36]:
X_xgb_train_aug, X_xgb_cv_aug, y_xgb_train, y_xgb_cv = train_test_split(X_train_aug, y_train, test_size=0.2)

In [34]:
# First col iare the weights
X_xgb_train = X_xgb_train_aug[:, 1:]
X_xgb_cv = X_xgb_cv_aug[:, 1:]
train_weights = X_xgb_train_aug[:, 0]
cv_weights = X_xgb_cv_aug[:, 0]

# XGBoost

In [27]:
import xgboost as xgb

In [28]:
train_dmatrix = xgb.DMatrix(data = X_xgb_train, label = y_xgb_train, weight = train_weights)
cv_dmatrix = xgb.DMatrix(data = X_xgb_cv, label = y_xgb_cv, weight = cv_weights)

In [42]:
watchlist = [(train_dmatrix, 'train'), (cv_dmatrix, 'cv')]
def custom_eval(preds, dtrain):
    labels = dtrain.get_label()
    return 'competition_score', competition_scorer(labels, preds)

Only had time to explore most important hyperparameters. My best attempt in the short remaining time is the following.

In [79]:
param = {'num_class':4,
         'max_depth':4,
         'min_child_weight':1.2,
         #'eta':0.3,
         'silent':1,
         'objective':'multi:softprob',
         'eval_metric':'mlogloss',
         'n_estimators':1000}
num_round = 500

In [80]:
bst = xgb.train(param, train_dmatrix, num_round, watchlist, feval = custom_eval, early_stopping_rounds = 50)

[0]	train-mlogloss:1.2488	cv-mlogloss:1.2496	train-competition_score:1.2488	cv-competition_score:1.2496
Multiple eval metrics have been passed: 'cv-competition_score' will be used for early stopping.

Will train until cv-competition_score hasn't improved in 50 rounds.
[1]	train-mlogloss:1.16125	cv-mlogloss:1.16338	train-competition_score:1.16125	cv-competition_score:1.16338
[2]	train-mlogloss:1.10085	cv-mlogloss:1.1042	train-competition_score:1.10085	cv-competition_score:1.1042
[3]	train-mlogloss:1.05777	cv-mlogloss:1.0625	train-competition_score:1.05777	cv-competition_score:1.0625
[4]	train-mlogloss:1.02684	cv-mlogloss:1.03312	train-competition_score:1.02684	cv-competition_score:1.03312
[5]	train-mlogloss:1.00364	cv-mlogloss:1.01051	train-competition_score:1.00364	cv-competition_score:1.01051
[6]	train-mlogloss:0.985455	cv-mlogloss:0.9933	train-competition_score:0.985455	cv-competition_score:0.9933
[7]	train-mlogloss:0.97056	cv-mlogloss:0.979541	train-competition_score:0.97056	cv-competition_score:0.979541
[8]	train-mlogloss:0.958954	cv-mlogloss:0.96896	train-competition_score:0.958954	cv-competition_score:0.96896
[9]	train-mlogloss:0.949874	cv-mlogloss:0.960565	train-competition_score:0.949874	cv-competition_score:0.960565
[10]	train-mlogloss:0.942433	cv-mlogloss:0.954141	train-competition_score:0.942433	cv-competition_score:0.954141
[11]	train-mlogloss:0.936304	cv-mlogloss:0.94905	train-competition_score:0.936304	cv-competition_score:0.94905
[12]	train-mlogloss:0.931415	cv-mlogloss:0.945016	train-competition_score:0.931415	cv-competition_score:0.945016
[13]	train-mlogloss:0.927268	cv-mlogloss:0.941326	train-competition_score:0.927268	cv-competition_score:0.941326
[14]	train-mlogloss:0.924209	cv-mlogloss:0.938549	train-competition_score:0.924209	cv-competition_score:0.938549
[15]	train-mlogloss:0.921543	cv-mlogloss:0.936562	train-competition_score:0.921543	cv-competition_score:0.936562
[16]	train-mlogloss:0.919315	cv-mlogloss:0.934702	train-competition_score:0.919315	cv-competition_score:0.934702
[17]	train-mlogloss:0.917393	cv-mlogloss:0.933014	train-competition_score:0.917393	cv-competition_score:0.933014
[18]	train-mlogloss:0.915704	cv-mlogloss:0.931876	train-competition_score:0.915704	cv-competition_score:0.931876
[19]	train-mlogloss:0.914294	cv-mlogloss:0.930979	train-competition_score:0.914294	cv-competition_score:0.930979
[20]	train-mlogloss:0.913032	cv-mlogloss:0.9301	train-competition_score:0.913032	cv-competition_score:0.9301
[21]	train-mlogloss:0.911966	cv-mlogloss:0.929327	train-competition_score:0.911966	cv-competition_score:0.929327
[22]	train-mlogloss:0.910622	cv-mlogloss:0.928342	train-competition_score:0.910622	cv-competition_score:0.928342
[23]	train-mlogloss:0.909709	cv-mlogloss:0.927707	train-competition_score:0.909709	cv-competition_score:0.927707
[24]	train-mlogloss:0.908686	cv-mlogloss:0.927369	train-competition_score:0.908686	cv-competition_score:0.927369
[25]	train-mlogloss:0.907792	cv-mlogloss:0.926773	train-competition_score:0.907792	cv-competition_score:0.926772
[26]	train-mlogloss:0.906561	cv-mlogloss:0.926285	train-competition_score:0.906561	cv-competition_score:0.926285
[27]	train-mlogloss:0.905958	cv-mlogloss:0.926065	train-competition_score:0.905958	cv-competition_score:0.926065
[28]	train-mlogloss:0.90542	cv-mlogloss:0.92584	train-competition_score:0.90542	cv-competition_score:0.92584
[29]	train-mlogloss:0.904393	cv-mlogloss:0.925495	train-competition_score:0.904393	cv-competition_score:0.925495
[30]	train-mlogloss:0.903706	cv-mlogloss:0.925236	train-competition_score:0.903706	cv-competition_score:0.925236
[31]	train-mlogloss:0.903165	cv-mlogloss:0.925112	train-competition_score:0.903165	cv-competition_score:0.925112
[32]	train-mlogloss:0.902689	cv-mlogloss:0.925044	train-competition_score:0.902689	cv-competition_score:0.925044
[33]	train-mlogloss:0.902197	cv-mlogloss:0.924621	train-competition_score:0.902197	cv-competition_score:0.924621
[34]	train-mlogloss:0.90177	cv-mlogloss:0.924679	train-competition_score:0.90177	cv-competition_score:0.924679
[35]	train-mlogloss:0.901209	cv-mlogloss:0.924574	train-competition_score:0.901209	cv-competition_score:0.924574
[36]	train-mlogloss:0.900961	cv-mlogloss:0.924443	train-competition_score:0.900961	cv-competition_score:0.924443
[37]	train-mlogloss:0.900527	cv-mlogloss:0.924484	train-competition_score:0.900527	cv-competition_score:0.924484
[38]	train-mlogloss:0.900007	cv-mlogloss:0.924263	train-competition_score:0.900007	cv-competition_score:0.924263
[39]	train-mlogloss:0.899397	cv-mlogloss:0.9242	train-competition_score:0.899397	cv-competition_score:0.9242
[40]	train-mlogloss:0.898629	cv-mlogloss:0.923759	train-competition_score:0.898629	cv-competition_score:0.923759
[41]	train-mlogloss:0.897897	cv-mlogloss:0.923522	train-competition_score:0.897897	cv-competition_score:0.923522
[42]	train-mlogloss:0.897646	cv-mlogloss:0.923396	train-competition_score:0.897646	cv-competition_score:0.923396
[43]	train-mlogloss:0.897163	cv-mlogloss:0.923237	train-competition_score:0.897163	cv-competition_score:0.923237
[44]	train-mlogloss:0.896708	cv-mlogloss:0.922925	train-competition_score:0.896708	cv-competition_score:0.922925
[45]	train-mlogloss:0.896397	cv-mlogloss:0.922895	train-competition_score:0.896397	cv-competition_score:0.922895
[46]	train-mlogloss:0.895853	cv-mlogloss:0.922783	train-competition_score:0.895853	cv-competition_score:0.922783
[47]	train-mlogloss:0.8954	cv-mlogloss:0.922591	train-competition_score:0.8954	cv-competition_score:0.922591
[48]	train-mlogloss:0.895138	cv-mlogloss:0.922673	train-competition_score:0.895138	cv-competition_score:0.922673
[49]	train-mlogloss:0.894766	cv-mlogloss:0.922526	train-competition_score:0.894766	cv-competition_score:0.922526
[50]	train-mlogloss:0.894295	cv-mlogloss:0.922544	train-competition_score:0.894295	cv-competition_score:0.922544
[51]	train-mlogloss:0.894058	cv-mlogloss:0.922474	train-competition_score:0.894058	cv-competition_score:0.922474
[52]	train-mlogloss:0.893833	cv-mlogloss:0.922337	train-competition_score:0.893833	cv-competition_score:0.922337
[53]	train-mlogloss:0.893666	cv-mlogloss:0.922444	train-competition_score:0.893666	cv-competition_score:0.922444
[54]	train-mlogloss:0.893214	cv-mlogloss:0.922304	train-competition_score:0.893214	cv-competition_score:0.922304
[55]	train-mlogloss:0.892981	cv-mlogloss:0.922157	train-competition_score:0.892981	cv-competition_score:0.922157
[56]	train-mlogloss:0.892427	cv-mlogloss:0.922239	train-competition_score:0.892427	cv-competition_score:0.92224
[57]	train-mlogloss:0.892033	cv-mlogloss:0.922464	train-competition_score:0.892033	cv-competition_score:0.922464
[58]	train-mlogloss:0.89158	cv-mlogloss:0.922719	train-competition_score:0.89158	cv-competition_score:0.922719
[59]	train-mlogloss:0.891138	cv-mlogloss:0.922601	train-competition_score:0.891138	cv-competition_score:0.922601
[60]	train-mlogloss:0.891028	cv-mlogloss:0.922687	train-competition_score:0.891028	cv-competition_score:0.922687
[61]	train-mlogloss:0.89072	cv-mlogloss:0.922683	train-competition_score:0.89072	cv-competition_score:0.922683
[62]	train-mlogloss:0.890187	cv-mlogloss:0.923085	train-competition_score:0.890187	cv-competition_score:0.923085
[63]	train-mlogloss:0.890037	cv-mlogloss:0.923115	train-competition_score:0.890037	cv-competition_score:0.923115
[64]	train-mlogloss:0.889844	cv-mlogloss:0.923222	train-competition_score:0.889844	cv-competition_score:0.923222
[65]	train-mlogloss:0.889687	cv-mlogloss:0.923084	train-competition_score:0.889687	cv-competition_score:0.923084
[66]	train-mlogloss:0.889589	cv-mlogloss:0.923096	train-competition_score:0.889589	cv-competition_score:0.923096
[67]	train-mlogloss:0.889499	cv-mlogloss:0.923052	train-competition_score:0.889499	cv-competition_score:0.923052
[68]	train-mlogloss:0.88932	cv-mlogloss:0.923093	train-competition_score:0.88932	cv-competition_score:0.923093
[69]	train-mlogloss:0.889066	cv-mlogloss:0.923148	train-competition_score:0.889066	cv-competition_score:0.923148
[70]	train-mlogloss:0.888662	cv-mlogloss:0.922984	train-competition_score:0.888662	cv-competition_score:0.922984
[71]	train-mlogloss:0.888433	cv-mlogloss:0.922842	train-competition_score:0.888433	cv-competition_score:0.922842

[72]	train-mlogloss:0.888326	cv-mlogloss:0.922833	train-competition_score:0.888325	cv-competition_score:0.922833
[73]	train-mlogloss:0.887885	cv-mlogloss:0.923071	train-competition_score:0.887885	cv-competition_score:0.923071
[74]	train-mlogloss:0.887773	cv-mlogloss:0.923124	train-competition_score:0.887773	cv-competition_score:0.923124
[75]	train-mlogloss:0.887552	cv-mlogloss:0.923233	train-competition_score:0.887552	cv-competition_score:0.923233
[76]	train-mlogloss:0.887432	cv-mlogloss:0.923374	train-competition_score:0.887432	cv-competition_score:0.923374
[77]	train-mlogloss:0.887193	cv-mlogloss:0.923237	train-competition_score:0.887193	cv-competition_score:0.923237
[78]	train-mlogloss:0.886756	cv-mlogloss:0.923467	train-competition_score:0.886756	cv-competition_score:0.923467
[79]	train-mlogloss:0.886591	cv-mlogloss:0.923486	train-competition_score:0.886591	cv-competition_score:0.923486
[80]	train-mlogloss:0.886275	cv-mlogloss:0.923402	train-competition_score:0.886275	cv-competition_score:0.923402
[81]	train-mlogloss:0.886066	cv-mlogloss:0.923371	train-competition_score:0.886066	cv-competition_score:0.923371
[82]	train-mlogloss:0.885926	cv-mlogloss:0.92333	train-competition_score:0.885926	cv-competition_score:0.92333
[83]	train-mlogloss:0.885788	cv-mlogloss:0.923339	train-competition_score:0.885788	cv-competition_score:0.923339
[84]	train-mlogloss:0.885625	cv-mlogloss:0.923331	train-competition_score:0.885625	cv-competition_score:0.923331
[85]	train-mlogloss:0.885287	cv-mlogloss:0.92348	train-competition_score:0.885287	cv-competition_score:0.92348
[86]	train-mlogloss:0.884839	cv-mlogloss:0.923423	train-competition_score:0.884839	cv-competition_score:0.923423
[87]	train-mlogloss:0.884404	cv-mlogloss:0.923656	train-competition_score:0.884404	cv-competition_score:0.923656
[88]	train-mlogloss:0.884299	cv-mlogloss:0.923579	train-competition_score:0.884299	cv-competition_score:0.923579
[89]	train-mlogloss:0.884229	cv-mlogloss:0.923565	train-competition_score:0.884229	cv-competition_score:0.923565
[90]	train-mlogloss:0.883925	cv-mlogloss:0.923609	train-competition_score:0.883925	cv-competition_score:0.923609
[91]	train-mlogloss:0.883706	cv-mlogloss:0.923502	train-competition_score:0.883706	cv-competition_score:0.923502
[92]	train-mlogloss:0.883605	cv-mlogloss:0.923495	train-competition_score:0.883605	cv-competition_score:0.923495
[93]	train-mlogloss:0.883207	cv-mlogloss:0.92352	train-competition_score:0.883207	cv-competition_score:0.92352
[94]	train-mlogloss:0.883008	cv-mlogloss:0.923663	train-competition_score:0.883008	cv-competition_score:0.923663
[95]	train-mlogloss:0.882862	cv-mlogloss:0.924055	train-competition_score:0.882862	cv-competition_score:0.924055
[96]	train-mlogloss:0.882658	cv-mlogloss:0.924437	train-competition_score:0.882658	cv-competition_score:0.924437
[97]	train-mlogloss:0.882523	cv-mlogloss:0.924383	train-competition_score:0.882523	cv-competition_score:0.924383
[98]	train-mlogloss:0.882403	cv-mlogloss:0.924477	train-competition_score:0.882403	cv-competition_score:0.924477
[99]	train-mlogloss:0.88233	cv-mlogloss:0.92451	train-competition_score:0.88233	cv-competition_score:0.924509
[100]	train-mlogloss:0.882134	cv-mlogloss:0.924689	train-competition_score:0.882134	cv-competition_score:0.924689
[101]	train-mlogloss:0.882072	cv-mlogloss:0.924857	train-competition_score:0.882072	cv-competition_score:0.924857
[102]	train-mlogloss:0.881961	cv-mlogloss:0.92485	train-competition_score:0.881961	cv-competition_score:0.92485
[103]	train-mlogloss:0.881844	cv-mlogloss:0.924905	train-competition_score:0.881844	cv-competition_score:0.924904
[104]	train-mlogloss:0.881723	cv-mlogloss:0.924965	train-competition_score:0.881723	cv-competition_score:0.924965
[105]	train-mlogloss:0.881663	cv-mlogloss:0.924967	train-competition_score:0.881663	cv-competition_score:0.924967
Stopping. Best iteration:
[55]	train-mlogloss:0.892981	cv-mlogloss:0.922157	train-competition_score:0.892981	cv-competition_score:0.922157

In [81]:
preds = bst.predict(cv_dmatrix)
competition_scorer(y_xgb_cv, preds)

0.9249671148676107

# Predict

In [82]:
test_dmatrix = xgb.DMatrix(data = X_test_enc)

In [83]:
y_test_predicted_probs = bst.predict(test_dmatrix)

# Submit

In [84]:
submission_df = pd.DataFrame({#'product_id':np.arange(X_test.shape[0]),
                              '0':requests_test['request_id'],
                              '1':y_test_predicted_probs[:, 0],
                              '2':y_test_predicted_probs[:, 1],
                              '3':y_test_predicted_probs[:, 2],
                              '4':y_test_predicted_probs[:, 3]})

In [85]:
submission_df.head(10)

                                  0         1         2         3         4
0  7a2f7215846392375b7e5f4a416298aa  0.004191  0.100471  0.783671  0.111668
1  f9388302f1a12ff58a9cabad201b24c4  0.040379  0.131103  0.601500  0.227018
2  482f122fbc7333eda62ca9efee6fbeb2  0.004483  0.121098  0.563920  0.310499
3  0676b42f6d679cfaee0e2633fc793a00  0.062231  0.091025  0.450553  0.396191
4  c857c384143351e1baf335648508e8c5  0.004251  0.195008  0.549240  0.251502
5  bd3a8a9baefd74922d8519693cfce0fe  0.060439  0.052258  0.485847  0.401456
6  96bf8268d973ad87a572893ee8378be3  0.027383  0.117979  0.525287  0.329351
7  09da6eb09639b4d0b9e87761ca585d23  0.040379  0.131103  0.601500  0.227018
8  c7311d1d63491975467283c6d6dad36f  0.039004  0.151976  0.572005  0.237015
9  34dc3716f07301c6bf1f4a062a669bf5  0.101141  0.025885  0.261390  0.611584

In [86]:
import io, math, requests

def submit_prediction(df, sep=',', comment='', compression='gzip', **kwargs):
    TOKEN='foo'
    URL='https://qscore.datascience-olympics.com/api/submissions'
    df.to_csv('temporary.dat', sep=sep, compression=compression, **kwargs)
    r = requests.post(URL, headers={'Authorization': 'Bearer {}'.format(TOKEN)},files={'datafile': open('temporary.dat', 'rb')},data={'comment':comment, 'compression': compression})
    if r.status_code == 429:
        raise Exception('Submissions are too close. Next submission is only allowed in {} seconds.'.format(int(math.ceil(int(r.headers['x-rate-limit-remaining']) / 1000.0))))
    if r.status_code != 200:
        raise Exception(r.text)

In [87]:
submit_prediction(submission_df, sep=',', index=False, comment='my submission')